#pragma once
#include "fmt.h"
#include "math.h"
#include "strings.h"
#include "ymf/ymfdata.h"
namespace ymfdata = ymf::ymfdata;
typedef struct __Channel {
	int channelID;
	int midiChannelID;
	Chip *chip;
	int fnum;
	int kon;
	int block;
	int alg;
	int panpot;
	int chpan;
	int volume;
	int expression;
	int velocity;
	int bo;
	float64 feedbackBlendPrev;
	float64 feedbackBlendCurr;
	float64 feedback1Prev;
	float64 feedback1Curr;
	float64 feedback3Prev;
	float64 feedback3Curr;
	float64 feedbackOut1;
	float64 feedbackOut3;
	float64 attenuationCoef;
	gopkg_in::but80::fmfm_core_v1::ymf::ymfdata::Frac64 modIndexFrac64;
	gopkg_in::but80::fmfm_core_v1::ymf::ymfdata::Frac64 lfoFrequency;
	float64 panCoefL;
	float64 panCoefR;
	operator *operators[4];
} Channel;
